---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y"
