---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y"
