---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: stunner-gateway-operator
  namespace: desktop
spec:
  interval: 30m
  chart:
    spec:
      chart: stunner-gateway-operator
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: stunner
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
