---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: registry
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-device-plugin
      version: 2.2.3
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    config:
      map:
        default: |-
        version: v1
        flags:
          migStrategy: "none"
          failOnInitError: true
          nvidiaDriverRoot: "/"
          plugin:
            passDeviceSpecs: false
            deviceListStrategy: envvar
            deviceIDStrategy: uuid
