apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ERBqMoLLvB4EcLvthOrWrK6TnyZSuWKUFHaQTU0PqfTTo4M5,iv:EMMz+QKQzOJ6JGVVAa14EORKo2xCa4DaohYBnSQDlWE=,tag:zmWag02dF6PqA/52z5x4/w==,type:str]
    credentials.json: ENC[AES256_GCM,data:eb5OUs/4qN4J25FsFMLzoEciRvzxHH6VgwV5Wybnq7c0mxtycEChD9F/sDisdGmihxw0+bkWKZOayjgdffxwP5iyB3/YaifxCFHHFSRce7s/URF7KM6SBA4wc2i1sc9aZY7/WraH/x/HZSo6nCHenIMjGJOqeJt4Z8+4lw9nD4zepWgaf8r1qhyyZew5HJ9dml7ck3MYk+S5IPysnTrp4bMWY2geT0oWpCDYrR6mVA==,iv:ed1HYuUcarqsvaJH1ccNYZgzH6OGusDrtkTyM/WPsok=,tag:P0/5pVz/DfALAS6jRMJXAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWFRqZjFDWjk1R1pqd2s4
            NGhJK3UwL25lM1dDa04xd0NHN1d0Y0dycHpjCmIrQW1pUk9iUU92NVFYaWc3cEFL
            YVR0ZGdoeFFQV1prblBpaTdrK05ETWsKLS0tIFJzb1c5QTRsaU04STFFNCs3eGFO
            ZHl1aGFqcjUwOUpxa3YzRVBOMHQwRWsKyGgUl4m73n7fk+YGF7r3pb6MXpQveYJE
            JE4fk7rnHpWd82nL+z1O+tY+eaZvCxcdAT0NwixR+hoHhbYTd4GmXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T19:31:28Z"
    mac: ENC[AES256_GCM,data:XQL4AXaMEv3R7FfpqxiiMHtzA1NgUqgjYPDZ+y3e3nab0jQvciv7AQXVBPRFYpOr4TH0oKp5TqId5rbnCRNwX9ShfgR8Htnl6ND1Mz1wkJSoqcEBNsDmMkSu0OjSRgVjCTyOOr9/Vz7oB8mL4PMV1Lag/5bKtxOhcveBK9mo0zc=,iv:IkYJRDzPlr7tPEl8RuKfcHYKkQuipjqb78L0AF56JkM=,tag:em4y7K/YBSYyA2lU/K1kgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
