apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: driver-config-secret
    namespace: democratic-csi
    labels:
        app.kubernetes.io/name: democratic-csi
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:afLLGwi1BreqYdDIufomVq2u+e+eyYgKUd1hXOaBIWAIBz6mD0+v2N1YI4ZtfsdVUmlaEUKUtTKmT+YZ0L8/WP2/rsimWfqu/acvLTV+dGcgIY7P9kmgVqRfcL08joDOYCBumY/hukcpttOOoxyRD/qApZ0SU+ZilzmmjZ/EAGcHrjRdPtJEr4lRkyWcFlUfP8upy3By081bmKHd72v3P03jZlhZSZgSTr1HoLQwwuSXjWumpupmrGvzmUozu23RA8/lRc7zFnIb+Mh82efFdZLxMTqRFQsRyozhBJpczcgLBQfnw5ndF+ZdwN6ySg7mCUac9EJOzLFa5fzQonAXvG2Hp7yXm19C22iXUj/anU1zDd3uD1yqvoJuoCCSide3vrWNbevs0o13hz5G1D8QFE0nywJmVFHn4l6y61R8c39UUc1gdmfOIZGmUWZxnwAcee4Y4JPkG9P0rtjvP8SpB7PytZ3OUmaD6NXySGI6ohyv5XroOVYKHDXG+ay/COZdMomgWlB3AhmTLyZmjXxwX5VTfV9Pep41HEQbrBOu+7yrnFCXAFVWliLgrH9mxahHIENQoGcDpSyUqDeFYaDf37kqOsDYZOuN/3HkYkg7pKlg0CUSOlDA7ju7HXXBUDoKQP7s/XkR+aKsnT7/XErK86o4yAUXJ+KuTUiqmTh+NVP9icBLpoE0BYtuItiikSjH0mZna1MLq+Xd/0+vm0et65yGpucRRm/OVYnKlv4fjxZ/GjYB1upBKa3q2W15EhO4axhRrVVx1JjhhAjZ19TTjNYePb+HteVZIw52KY3P08wfpXEpB6pMbVepecAKabCBEfawTZ5QuJ5/9Q26dta871SKEEjIhcBjoMkl4Q4=,iv:/uCVZQPrXmoD2QFRhyhOLHsb2al69ESrCsZNZuju8CA=,tag:Rz8lVdMxFQBxrEFSzaWSTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTEhUNHMreUVnby9nb0w1
            b1I0K0NNL054aTB0R2hLaTdBa0tuYU55K1IwCk1QYkR2S01OUzM1ZTRrRW5NRjFh
            MkFlTjZZRmw1eElRcWcrbWlJVGZHWVkKLS0tIE5SbmtibTRza0F5QWtRaEU5Q0tm
            NUZTRDZjOFVqamtZcmlVenlvSDRQd1kKl7bF2vNpflODiPjDx+Bz/5IPEOB2ytQ0
            ZsaYp0FMOmKs/bIF+wCWSWcwaKqIuXsN08GkGdxtaRRQ1UkXVnbKnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T22:25:55Z"
    mac: ENC[AES256_GCM,data:1yfdc5l2WUBrt9/zo8Loy5GLLUa40vz1L5HD4BhdNbtQTao3G/ol8NwG5J23nT4fIRShMKbqC/o3fmEdTekL4oIjqfA+uoAyJnyACOXLx70nrBkz/47KdMW/YLeBqfKpqqxL4yW1rcRebz9o+g1fJPIxvLLCxQj9D66yVMUC+UM=,iv:hVkzvbUdJrF4lXiv8dbonuS8BSSOlB1+HTNHwZO5y6E=,tag:LEZm2aXRibArxwiWy7pdrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
