kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-nfs
  namespace: democratic-csi
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
