apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:kAyaD3hm55lF6ds6BpO6w3D58tPtwUdcTP6fWLqlVhtFBtGHtsGk9Q==,iv:Ndwc5rGWcD1A/rusMwDUqoxgx+lPWqC24U3Fd1rxpD0=,tag:tmBnlOMwzFN7iq9mM1WGqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Vjkxc1hzVXRndWM4dnY5
            T1drSzJpWWROMU5sZHRiTlZ1a1dXYUZoRHpZClc1MVFrNWN6Q2g4Z0V5NGN5eWta
            UzFFUy9HTTk4b0lOWGxRRWtLdHhZSVUKLS0tIE1qam9Tam9iRDVEZnZ2QnVCRG1o
            Rjg5Y25aelRLT0wveU05RituTWtOcmcKv6Gle4qs46ySWnb+plrVLydoDCoX/4KL
            TmkKoM0Xzqp7HDjwbd0rmHPNt/EUb1Y593lMawGPcJLwDZhd5YNagA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T17:19:54Z"
    mac: ENC[AES256_GCM,data:moMfUkDZ5QM74ad5ifeO4fhBEsdZt32+m9nTczNfedIAf2g0/cPyu9vxfONiaZK7WCaEHIgd++Z/OQHR+FwDCzZmeDgkGMNRXlRjAEO/w4TVTSujWwNodWOJg2qSA03e8hXUTUhAd0i72oFqLDB3/c5Puka9pvqa03ev7xG00kE=,iv:zqj/jearKfpcXBLRByHgCTpT+oT3RMd+4Qz78foEzZY=,tag:Bg/9qqjeSg98iUuvmYpu3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
