apiVersion: v1
kind: Secret
metadata:
    name: selkies-auth-secret
    namespace: selkies
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:tn8Fc5Sk,iv:fVM3QhIr3/k+uykR6UeFSmuhC5hUbEOnnisjVPGusvI=,tag:htUJUpEC72v6/5OK8JzWrA==,type:str]
    password: ENC[AES256_GCM,data:zjpWorL5c2CSYAqJzWL67Fsv,iv:cOJ07fEuU8dUCj3/nZ8bav6fYTfZYBJqH3Y+XJXaUuI=,tag:sWGfOzE8VnX2nWFk436lLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMnhOSFo5WkdXV2ZUajJM
            akpwRVFJd0xKVmhaNDJLZitWS2UzeWJ1QlRJCkF2bFBoNEg0SzB5Y3lmcXhtRnF3
            MUxSVVB6eHdqTDJhVzhyZHJwZ3FDa1kKLS0tIDdFY3RKNzcvYjc0SExPUExBMnpB
            VE5LN0VEU1RuOFNjcmQwTnF1MnZLS0UKR3ofhcVNmduOhgTYNjTCrAgYxNn/Qpxu
            KtAi1UpqZBEabccd3VGsMeEkw9jQCtwhP+5o/sijvIn3ytE0m2Z1Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T19:05:17Z"
    mac: ENC[AES256_GCM,data:KGA36LQWmo1pg1GTzI6PR++rgLG+PrpojDpqqlYuMm9OiwQCYwi2fNgOuZ0hO9RLjn7lESenjD3r0fRhy0WyLVTy06CiYaC+7QEOLCLq+3Mi5bPbeT5Plw0hNJAGfdWz0GNcAMXNf9CHHjXaJg1ho0uj+LS7KJqsR2xcmdzBiNE=,iv:19tYpxPMZCLv+MwAbP9iAVe9zgk4EW3Vuv1AGbwQL3w=,tag:D9xT0ksqc2EYZOjgjmGkhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
