apiVersion: v1
kind: Secret
metadata:
    name: selkies-auth-secret
    namespace: desktop
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:cx18hcUx,iv:mnrlmR+9i0sa7A4pdvABvTXAht2sYaaR9I9wdQm0Dno=,tag:N0Rnh6SfV/lVthYQbH7exw==,type:str]
    password: ENC[AES256_GCM,data:fz4gigDEf8MR+S0pOmY2e2WO,iv:Gw9mvFVMtLuQoiXpAr/vsBJRSuARroMcfYbMEyj2ER0=,tag:7HCYkOzKTokDRTKKg9Lbbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMXk4b213bml0SXZuN1RK
            Um1icTd0R3JtdTJxeWxJTk1Xbi96ZnEzVGlrCmNWSHRCQU1wZ3VkdUVDb2p6VlNl
            blgzVXUzcVpYb05aOUhsN1NqMEQ1RFEKLS0tIGJmY3RnQjZaK0ZITEk2L0tKd0hW
            NGd1b24zV3JHMGtlYld4RHJpVDlSbUUKZKx1qZvYZBHID7kAXoV3p4cPfCVPx0+T
            n7eiCZirZyaN4R6LoVRhtkrvk5xE60TYEKAWIGL/wnHz00BQPZEqZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T20:00:01Z"
    mac: ENC[AES256_GCM,data:UXUNNPq2D9xDVr7WGcbsk8wP7ZZrDw9YQOJDodL1fjIsWI+OP0Irvkeo/2vZ3S5Ue9Y/OBYAAwUVWxvziiXzkbo7UInCcz2m9PnDj5FKEmS1neig754s5JMZibKK0k//NVaNaZWrVZCWgOoTE/KlbGVPdEPpZ1xhj1u9dQdeBp8=,iv:8Z5yajqwi9RHBm7dFNOE+WB7qfOzwgnC5EpeS7o8ybE=,tag:BNrt4yCaQD4GKi3AM258Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
