apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Y6Sq0SRYICMJIz86+wCxlmkv1MQYicL2X/exNAYRE0Y=,iv:IplEc9Xvb5nvLTtPhql0ei37dZag3+WETE0CmUzButo=,tag:k0S/Evuhx5V8SwAmRotykA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWTFlbWNmdUpoNnRVaTZG
            Rzd6OVZ0K3NEdENEM2Rwd0svUEpwR0crNFU4Cjd6amthWWpPQ2tFRmRLOXVEZTc1
            QVZFMEVqY1VWTTZOSjl6d0JWbEhDZTgKLS0tIGRycE9JbVV6STVrM2tpTDViazFF
            R05Eb0VJRVNsYlQ3V09qQ3BqMUVZRUEKU5XKIKLa4k1Hba8OG8gTwLONitZ4zRgu
            /WG2luNLGP35IC08WYvc8uV6LSjqzr6ohNM3gcK6u0DJnfqnmT1LaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T17:24:01Z"
    mac: ENC[AES256_GCM,data:ggT6w9JIRIrvHwUKfKy9FnjsKtXYyQ37W746AHA2tIgcDQw4h+kbsCv4phWqeo6ei7rsYvruMlLTundTqRvVUY7lfJz/wvuNaYvdod5ilv4aHuGNYqoR4K9BVMKa6chV5MrzZY6QNDqxNgMJwnM/PsobNUTd/1/Uwz+kV6PS/vM=,iv:KXlhCTMwxAzVKGoiDfri0jWHE0T/taWW05P9Ewtc464=,tag:KsHaT/ocJaujno7nuMNbBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
