apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:jcn+rcCPjmogmlvCThnR5v0nIiKATjKo4I6fwXa/9aEMrVHKv/oacg==,iv:VZ+hGHYzba12KTyGxt8PByuKfFgI8dtjGKXb+hZKw/g=,tag:r10FcO6fN9hLQLOzhcYrtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k92xt0gaglarme3xrmykcelx935l60epmrppzq6kmr4kht59tg0srux40y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST0lSSUZjR3ZDUDNqd3JT
            UWFYWUQ4NG55OHFLM0xoaVk0SHdxbjJFekE4Ckl6K1c1QThQMTY4NExSdVJTSmNp
            c1c4NWlUWTFEZlJOd3Y5aGRtbFozV28KLS0tIDErZlQwTkRaUEF1a2hnUTBqQTd2
            OTNZKzY5citsRUdTZkU4dlB5MVpBWEUKZhcGE9H1xGVXTw1R70flq9aHZSbY7TPq
            bzH3VTzsEhvpE0UhVhB2i6CiGryCjy7eXmsKtWa3+a2TDXcfWY8wxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T17:24:01Z"
    mac: ENC[AES256_GCM,data:XcWjVZ3WTQIZHCFKzrrmzU22DiAQj1ZL6WYiCRHNCIyUBbz5dhG9GSS2DyageIkRKGTVC/OxPUuyUc6XRMZnWFWcFajs148LBoM4/1rJgo5mx2omMYiSHcPpBIWIBhqWYSKKh1xWSq9DwxsDxO6BPArFLAWsjuk+X/GyyOO+YMw=,iv:xp40KCwH+HbW0vbDscw82hEyZaq7LkU5OPwKGIXwJy8=,tag:YlYn8gNnA5wPNB6rqGzEQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
